### PR TITLE
basic location search functionality

### PR DESCRIPTION
**Pull request by TheTrepanier**
changed portions of the ajax call files, set to variables to be called by the front end. Added basic location search functionality

### CODE REVIEW

**Review by Blair221 — COMMENTED** [review]
This looks really cool. I approve these changes but I still want to make sure Jon gets a peek before we merge to the sacred branch

**Comment by TheTrepanier** [comment]
I 100% agree we all should make sure that we take a look at this before we merge

**Comment by rjeasy** [comment]
Looks fine to me I see I missed a few things in the code I was writing.
I would only want to add  =>  $(document.body).on("click", "#navbar-event-button", navbarSearch);
at the bottom for the search event  button.

**Comment by TheTrepanier** [comment]
@rjeasy you can definitely add that bit of code to your branch and submit a pull request and then we'll be able to merge that into the master, since the event search portion is what you were working on.

**Review by reiko321 — APPROVED** [review]
Looks fine to me. run it.

**Pull request merged**
